spring:
  application:
    name: user-api

  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASS}
      port: ${MONGO_PORT}
      authentication-database: admin
      auto-index-creation: true
    cache:
      type: redis
      redis:
        time-to-live: 300
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}
logging:
  level:
    root: ${LOG_LEVEL:DEBUG}
  org:
    springframework:
      cache: ${LOG_LEVEL:TRACE}