spring:
  application:
    name: user-api
  cache: # https://docs.spring.io/spring-boot/reference/io/caching.html
    type: redis
    redis:
      time-to-live: 10m
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASS}
      port: ${MONGO_PORT}
      authentication-database: admin
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}

logging:
  level:
    root: ${LOG_LEVEL:DEBUG}
  org:
    springframework:
      cache: ${LOG_LEVEL:TRACE}